[package]
name = "switch_led_control"
version = "0.1.0"
authors = ["S-tatsuya_raspberry <s.tatsuya0123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"
ctrlc = "3.1.8"
